### ISSUE TITLE
Auto updates are broken.

### ISSUE THREAD

**Issue by SilkePilon** [the-lodestone-project/Lodestone#19]
**Describe the bug**
When lodestone checks for updates in pip and JavaScript it fails on systems where the python command is python3

**Comment by HellishBro** [comment]
literally just try except

**Comment by SilkePilon** [comment]
> literally just try except

This will just remove it. The issue is something else.

**Comment by HellishBro** [comment]
whats the issue. show logs

**Comment by SilkePilon** [comment]
its the same issue you got, with file not found when you run the bot

**Comment by SilkePilon** [comment]
![image](https://github.com/SilkePilon/Lodestone/assets/64040187/150b3cd6-42ba-4e28-8420-ddd2fc9c2dbf)
here
