### ISSUE TITLE
Make the Bug Request form much better. The body of this post is the new template.

### ISSUE THREAD

**Issue by KavyanshKhaitan2** [the-lodestone-project/Lodestone#41]
> ### **Describe the bug**

> ### **To Reproduce**

> ### **Expected behavior**

> ### **Screenshots**

> ### **Desktop (please complete the following information):**
 - OS: [e.g. windows, linux, macOS]
 - Python version: [e.g. 3.11]
 - Node version: [e.g. 22]

> ### **Additional context**

**Comment by KavyanshKhaitan2** [comment]
would you change it to this?

**Comment by KavyanshKhaitan2** [comment]
Also, need help in #40

**Comment by SilkePilon** [comment]
Thx, updated it!
