### ISSUE TITLE
Installs npm packages every time making startup much slower

### ISSUE THREAD

**Issue by KavyanshKhaitan2** [the-lodestone-project/Lodestone#42]
**Describe the bug**
Whenever started, it tries to install packages every time.

**To Reproduce**
Start any lodestone script.

**Expected behavior**
Installs packages once. Should make a config file or check if the package is already installed using npm list

**Screenshots**

**Desktop (please complete the following information):**
 - Should not matter (#41)

**Smartphone (please complete the following information):**
 - Should not matter (#41)

**Additional context**

**Comment by SilkePilon** [comment]
there is an skip checks flag in the createBot

**Comment by SilkePilon** [comment]
```py
ls_skip_checks=True,
```

**Comment by KavyanshKhaitan2** [comment]
Not in documentation. I am making a PR to fix that right now.

**Comment by HellishBro** [comment]
closed as its working as expected
